# Pythonによる制御工学入門（オーム社）
## Chapter 1 ~ 3

2022/2/6作成

In [1]:
import numpy as np
import control as ct
%matplotlib qt

In [2]:
# Page 67
Np = [1,2]
Dp = [1,5,3,4]

P = ct.tf(Np, Dp)
print(P)


        s + 2
---------------------
s^3 + 5 s^2 + 3 s + 4



In [3]:
# Page 68
s1 = ct.tf([1,3],[1])
s2 = ct.tf([1],[1,1])
s3 = ct.tf([1],[1,2])

P = s1*s2*s3**2
print(P)

[[Pnum]], [[Pden]] = ct.tfdata(P)
print(Pnum) #分子: numerator
print(Pden) #分母: denominator


        s + 3
---------------------
s^3 + 5 s^2 + 8 s + 4

[1 3]
[1 5 8 4]


In [4]:
# Page 75
A = '0 1; -1 -1'
B = '0; 1'
C = '1 0'
D = '0'

P = ct.ss(A,B,C,D)
print(P)

A = [[ 0.  1.]
     [-1. -1.]]

B = [[0.]
     [1.]]

C = [[1. 0.]]

D = [[0.]]



In [5]:
# Page 75
A = '1 1 2; 2 1 1; 3 4 5'
B = '2; 0; 1'
C = '1 1 0'
D = '1'

P = ct.ss(A,B,C,D)
print(P)
print('A=', P.A)
print('B=', P.B)
print('C=', P.C)
print('D=', P.D)

PA, PB, PC, PD = ct.ssdata(P)
print('A=', PA)
print('B=', PB)
print('C=', PC)
print('D=', PD)

A = [[1. 1. 2.]
     [2. 1. 1.]
     [3. 4. 5.]]

B = [[2.]
     [0.]
     [1.]]

C = [[1. 1. 0.]]

D = [[1.]]

A= [[1. 1. 2.]
 [2. 1. 1.]
 [3. 4. 5.]]
B= [[2.]
 [0.]
 [1.]]
C= [[1. 1. 0.]]
D= [[1.]]
A= [[1. 1. 2.]
 [2. 1. 1.]
 [3. 4. 5.]]
B= [[2.]
 [0.]
 [1.]]
C= [[1. 1. 0.]]
D= [[1.]]


In [6]:
# Page 82
S1 = ct.tf([1],[1,1])
S2 = ct.tf([1],[1,2])
S3 = ct.tf([3,1],[1,0])
S4 = ct.tf([2,0],[1])

Sa = ct.feedback(S1,S2)
Sb = ct.series(S3,Sa)
Sc = ct.feedback(Sb,S4)

print(Sc)


  3 s^2 + 7 s + 2
--------------------
7 s^3 + 17 s^2 + 7 s

